name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Cypress tests with Allure
      - name: Run Cypress tests with Allure
        uses: cypress-io/github-action@v5
        with:
          command: npm run test-with-allure

      # Step 4.1: Generate Allure report
      - name: Generate Allure report
        run: |
          npx allure generate allure-results --clean -o allure-report

      # Step 5: Upload Allure HTML report as an artifact
      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: Allure HTML Report
          path: allure-report

      # Step 6: Email Allure report
      - name: Email Allure Report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: Akinloose Emmanuel Temidayo SDET
          subject: Allure Test Report
          to: emmanuelakinloose2@gmail.com,eakinloose@gmail.com
          body: |
            Hello,

            Please find the attached Allure test report for the most recent regression tests run on our application.

            To view the results:
            1. Download the attached file.
            2. Open the `index.html` file inside the downloaded folder using your preferred web browser.

            Best regards,  
            Akinloose Emmanuel Temidayo  
            Software Development Engineer in Test (SDET)
          attachments: allure-report
