name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run regression-pack

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html

      - name: Email Report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: Akinloose Emmanuel Temidayo SDET
          subject: Cypress Test Report
          to: emmanuelakinloose2@gmail.com,eakinloose@gmail.com,rebecca.dibie@sterling.ng
          body: |
            Hello,

            I hope this email finds you well.

            Please find the attached Cypress test report for the most recent regression tests run on our application.

            To view the results:
            1. Download the attached file: **index.html**.
            2. Open the file using your preferred web browser (e.g., Chrome, Firefox, Edge, etc.).

            This will open the full test report with detailed results, including passed and failed tests, along with any relevant information and logs.

            If you have any questions or need further details, feel free to reach out.

            Best regards,  
            Akinloose Emmanuel Temidayo  
            Software Development Engineer in Test (SDET)
          attachments: cypress/reports/html/index.html
